package repomap

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/flanksource/repomap/kubernetes"
)

type FileMap struct {
	Path           string
	Scopes         Scopes                    `yaml:"scope,omitempty"`
	Language       string                    `yaml:"language,omitempty"`
	Tech           Technology                `yaml:"tech,omitempty"`
	Ignored        bool                      `yaml:"ignored,omitempty"`
	KubernetesRefs []kubernetes.KubernetesRef `yaml:"kubernetes_refs,omitempty" json:"kubernetes_refs,omitempty"`
}

type Author struct {
	Name     string    `json:"name,omitempty"`
	Email    string    `json:"email,omitempty"`
	Date     time.Time `json:"date,omitempty"`
	GithubID string    `json:"github_id,omitempty"`
}

type SourceChangeType string

const (
	SourceChangeTypeAdded      SourceChangeType = "added"
	SourceChangeTypeModified   SourceChangeType = "modified"
	SourceChangeTypeDeleted    SourceChangeType = "deleted"
	SourceChangeTypeRenamed    SourceChangeType = "renamed"
	SourceChangeTypeDocumented SourceChangeType = "documented"
	SourceChangeTypeTested     SourceChangeType = "tested"
	SourceChangeTypeRefactored SourceChangeType = "refactored"
	SourceChangeTypeConfigured SourceChangeType = "configured"
	SourceChangeTypeOptimized  SourceChangeType = "optimized"
	SourceChangeTypeFixed      SourceChangeType = "fixed"
	SourceChangeTypeUpgraded   SourceChangeType = "upgraded"
	SourceChangeTypeScaled     SourceChangeType = "scaled"
)

type LineRanges string

func NewLineRanges(lines []int) LineRanges {
	if len(lines) == 0 {
		return ""
	}

	sorted := make([]int, len(lines))
	copy(sorted, lines)
	for i := 0; i < len(sorted); i++ {
		for j := i + 1; j < len(sorted); j++ {
			if sorted[i] > sorted[j] {
				sorted[i], sorted[j] = sorted[j], sorted[i]
			}
		}
	}

	var ranges []string
	start := sorted[0]
	end := sorted[0]

	for i := 1; i < len(sorted); i++ {
		if sorted[i] == end+1 {
			end = sorted[i]
		} else {
			if start == end {
				ranges = append(ranges, fmt.Sprintf("%d", start))
			} else {
				ranges = append(ranges, fmt.Sprintf("%d-%d", start, end))
			}
			start = sorted[i]
			end = sorted[i]
		}
	}

	if start == end {
		ranges = append(ranges, fmt.Sprintf("%d", start))
	} else {
		ranges = append(ranges, fmt.Sprintf("%d-%d", start, end))
	}

	return LineRanges(strings.Join(ranges, ","))
}

func (lr LineRanges) String() string {
	return string(lr)
}

type CommitChange struct {
	File  string            `json:"file,omitempty"`
	Node  string            `json:"node,omitempty"`
	Type  SourceChangeType  `json:"type,omitempty"`
	Scope Scopes            `json:"scopes,omitempty"`
	Tech  []ScopeTechnology `json:"tech,omitempty"`
	Adds  int               `json:"adds,omitempty"`
	Dels  int               `json:"dels,omitempty"`
	// Line numbers that were changed (additions only, in the new file) compressed into ranges
	LinesChanged      LineRanges                    `json:"lines_changed,omitempty"`
	KubernetesChanges []kubernetes.KubernetesChange `json:"kubernetes_changes,omitempty"`
	Severity          Severity                      `json:"severity,omitempty"`
}

type Commit struct {
	Hash      string            `json:"hash,omitempty"`
	Author    Author            `json:"author,omitempty"`
	Committer Author            `json:"committer,omitempty"`
	Headers   map[string]string `json:"headers,omitempty"`
	// First line of commit message
	Subject string `json:"subject,omitempty"`
	// Everything after the first line of the commit message
	Body  string `json:"body,omitempty"`
	Patch string `json:"patch,omitempty"`
	// e.g. Signed-off-by, Co-authored-by
	Trailers map[string]string `json:"trailers,omitempty"`
	// Any #references found in the subject
	Reference string `json:"reference,omitempty"`
	// Conventional commits
	CommitType CommitType `json:"commit_type,omitempty"`
	Scope      ScopeType  `json:"scope,omitempty"`
	// e.g [SKIPCI] [AUTOGENERATED] added as prefixes or suffixes
	Tags         []string `json:"tags,omitempty"`
	QualityScore int      `json:"score,omitempty"`
}

func (c Commit) AsMap() map[string]any {
	return map[string]any{
		"hash":         c.Hash,
		"date":         c.Author.Date,
		"author":       c.Author.Name,
		"author.email": c.Author.Email,
		"subject":      c.Subject,
		"body":         c.Body,
		"commit_type":  c.CommitType,
		"scope":        c.Scope,
		"patch":        c.Patch,
	}
}

type FilePatch struct {
	OldPath   string
	NewPath   string
	IsNew     bool
	IsDeleted bool
	Patch     string
}

func (c *Commit) ParsePatch() []FilePatch {
	var patches []FilePatch
	lines := strings.Split(c.Patch, "\n")

	var currentPatch *FilePatch
	var patchLines []string

	for _, line := range lines {
		if strings.HasPrefix(line, "diff --git ") {
			if currentPatch != nil {
				currentPatch.Patch = strings.Join(patchLines, "\n")
				patches = append(patches, *currentPatch)
			}
			currentPatch = &FilePatch{}
			patchLines = []string{line}

			parts := strings.Fields(line)
			if len(parts) >= 4 {
				currentPatch.OldPath = strings.TrimPrefix(parts[2], "a/")
				currentPatch.NewPath = strings.TrimPrefix(parts[3], "b/")
			}
		} else if currentPatch != nil {
			patchLines = append(patchLines, line)
			if strings.Contains(line, "new file mode") {
				currentPatch.IsNew = true
			} else if strings.Contains(line, "deleted file mode") {
				currentPatch.IsDeleted = true
			}
		}
	}

	if currentPatch != nil {
		currentPatch.Patch = strings.Join(patchLines, "\n")
		patches = append(patches, *currentPatch)
	}

	return patches
}

func (c *Commit) GetFilePatch(filePath string) string {
	patches := c.ParsePatch()
	for _, p := range patches {
		if p.NewPath == filePath || p.OldPath == filePath {
			return p.Patch
		}
	}
	return ""
}

type Changes []CommitChange

func (c Changes) Summary() CommitChange {
	if len(c) == 1 {
		return c[0]
	}
	summary := CommitChange{}
	scopes := make(map[ScopeType]struct{})
	types := make(map[SourceChangeType]struct{})
	techs := make(map[ScopeTechnology]struct{})
	for _, change := range c {
		summary.Adds += change.Adds
		summary.Dels += change.Dels
		for _, scope := range change.Scope {
			scopes[scope] = struct{}{}
		}
		types[change.Type] = struct{}{}
		for _, t := range change.Tech {
			techs[t] = struct{}{}
		}
	}

	for scope := range scopes {
		summary.Scope = append(summary.Scope, scope)
	}
	if len(types) == 1 {
		for t := range types {
			summary.Type = t
		}
	}
	for t := range techs {
		summary.Tech = append(summary.Tech, t)
	}

	return summary
}

type CommitAnalysis struct {
	Commit  `json:",inline"`
	Tech    []ScopeTechnology `json:"tech,omitempty"`
	Changes Changes           `json:"changes,omitempty"`
	// Original commit before analysis
	Original Commit `json:"-"`
	// Pre-computed metrics for performance
	TotalLineChanges   int `json:"-"`
	TotalResourceCount int `json:"-"`
}

func (ca CommitAnalysis) GetScopes() Scopes {
	scopesSet := make(map[ScopeType]struct{})
	for _, change := range ca.Changes {
		for _, scope := range change.Scope {
			scopesSet[scope] = struct{}{}
		}
	}
	var scopes Scopes
	for s := range scopesSet {
		scopes = append(scopes, s)
	}
	return scopes
}

func (ca CommitAnalysis) IsAnalyzed() bool {
	if ca.Original.Hash == "" {
		return false
	}
	return ca.Scope != ca.Original.Scope ||
		ca.CommitType != ca.Original.CommitType ||
		ca.Body != ca.Original.Body ||
		ca.Subject != ca.Original.Subject
}

func (ca CommitAnalysis) AsMap() map[string]any {
	m := ca.Commit.AsMap()
	m["scope"] = ca.Scope
	m["commit_type"] = ca.CommitType
	m["tech"] = ca.Tech
	m["changes"] = ca.Changes
	return m
}

type CommitAnalyses []CommitAnalysis

func (ca CommitAnalyses) From() time.Time {
	if len(ca) == 0 {
		return time.Time{}
	}
	earliest := ca[0].Author.Date
	for _, analysis := range ca {
		if analysis.Author.Date.Before(earliest) {
			earliest = analysis.Author.Date
		}
	}
	return earliest
}

func (ca CommitAnalyses) To() time.Time {
	if len(ca) == 0 {
		return time.Time{}
	}
	latest := ca[0].Author.Date
	for _, analysis := range ca {
		if analysis.Author.Date.After(latest) {
			latest = analysis.Author.Date
		}
	}
	return latest
}

type ScanResult struct {
	Files  []FileMap
	Errors []ScanError
}

type ScanError struct {
	Path string
	Err  error
}

func (e ScanError) Error() string {
	return e.Path + ": " + e.Err.Error()
}

type FileReader interface {
	ReadFile(path string) (string, error)
	FileExists(path string) bool
	Walk(root string, fn fs.WalkDirFunc) error
}

type OSFileReader struct{}

func (r OSFileReader) ReadFile(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

func (r OSFileReader) FileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func (r OSFileReader) Walk(root string, fn fs.WalkDirFunc) error {
	return filepath.WalkDir(root, fn)
}
